# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(268, 666)
        MainWindow.setMinimumSize(QtCore.QSize(268, 666))
        MainWindow.setMaximumSize(QtCore.QSize(268, 666))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_power = QtWidgets.QPushButton(self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(10, 10, 75, 71))
        self.button_power.setObjectName("button_power")
        self.button_channelUp = QtWidgets.QPushButton(self.centralwidget)
        self.button_channelUp.setGeometry(QtCore.QRect(164, 140, 91, 81))
        self.button_channelUp.setObjectName("button_channelUp")
        self.button_channelDown = QtWidgets.QPushButton(self.centralwidget)
        self.button_channelDown.setGeometry(QtCore.QRect(164, 230, 91, 81))
        self.button_channelDown.setObjectName("button_channelDown")
        self.button_volumeUp = QtWidgets.QPushButton(self.centralwidget)
        self.button_volumeUp.setGeometry(QtCore.QRect(10, 140, 91, 81))
        self.button_volumeUp.setObjectName("button_volumeUp")
        self.button_volumeDown = QtWidgets.QPushButton(self.centralwidget)
        self.button_volumeDown.setGeometry(QtCore.QRect(10, 230, 91, 81))
        self.button_volumeDown.setObjectName("button_volumeDown")
        self.button_mute = QtWidgets.QPushButton(self.centralwidget)
        self.button_mute.setGeometry(QtCore.QRect(20, 340, 231, 23))
        self.button_mute.setObjectName("button_mute")
        self.tv_output_label = QtWidgets.QLabel(self.centralwidget)
        self.tv_output_label.setGeometry(QtCore.QRect(26, 390, 221, 201))
        self.tv_output_label.setText("")
        self.tv_output_label.setObjectName("tv_output_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote"))
        self.button_power.setText(_translate("MainWindow", "Power"))
        self.button_channelUp.setText(_translate("MainWindow", "Channel Up"))
        self.button_channelDown.setText(_translate("MainWindow", "Channel Down"))
        self.button_volumeUp.setText(_translate("MainWindow", "Volume Up"))
        self.button_volumeDown.setText(_translate("MainWindow", "Volume Down"))
        self.button_mute.setText(_translate("MainWindow", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
